
name: github pages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Install dependencies
        run: npm ci

      - name: Build production website
        run: npm run build:ci
      
      - name: Make copy of index.html 
        run: |
          chmod u+x "${GITHUB_WORKSPACE}/copyfile.sh"
          bash "${GITHUB_WORKSPACE}/copyfile.sh"
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.REACT_GH_PAGE }}
          publish_dir: ./dist/sample
